env:
  global:
  - COMMIT_AUTHOR_EMAIL: alfacoins@users.noreply.github.com
language: python
dist: trusty
python: '3.6'
branches:
  only:
  - master
  - nightly
  - "/^v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
addons:
  apt:
    packages:
    - libpq-dev
install: "./scripts/travis-install.sh"
script: py.test --cov=alfacoins_api_python
after_success: travis_retry coveralls
deploy:
  provider: pypi
  user: __token__
  skip_cleanup: true
  password:
    secure: "BK2haX9gRyr9tZNR1qiP4vvh0b6r0z/s/6FCcG5DVUSN9GLvcgozU3+S3J1k8jPC7cIF0pPGZkddRjZWoLg4kBmXN5f2PXuI8cp2zmjKVZdLTgDJIjK2IRBzkEtCSdcjPg/McH6ULlagouPr1qXC2q935GNwgJ2a0opYgNtaI+RRJm41b/DQRPal9W1jO4VNh79BwmI8oi0Ya8v2B/vv8v1iAf1ea7aedjTP7XQRvi6UkPY0z+Y+B4NxO7cMDTm0kzT1WjCWd4+zW6Q5xQVsM0hcpwTbuzlqM5i4fhDo2ygdOxwLI8+D2MUsCbBZn+6G704EBiKbw7hXIEhFbSwW2TaLJ2jbaWGp28MteyeDjzSvTYdWRZI9pRFU+ngbML1KR5LKQxERqzsJYCRr7qMXg2jJ7wmGBsAXxj9VFstIpVOlzKNWZMJRQsIiE1d2uwGIaU6WXEx5qH1ZzZsBLdGsWUs+WctmEX+9zZvuhG/6xMBfaKbF5PTHZc9VeTWPX0BDKAlckZTqXebZyxaUU+R0ehw4l69MxQVS2S51b6A7+a7j7ApRfNnHij8EisEJeHfYwnF5xGZsX9ZU1Q3SDbZ/h8gFQwQLEeXoqpfPKZpyH434Y4bcDywtNrwfhNJr7u8wjczwiA1vRJ15YDxXTEgBw+tG4OngHAGfqszDG73NdBw=" 
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ALFAcoins/alfacoins-api-python
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
