env:
  global:
  - COMMIT_AUTHOR_EMAIL: arash.fattahzade@carrene.com
language: python
dist: trusty
python: '3.6'
branches:
  only:
  - master
  - nightly
  - "/^v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
addons:
  apt:
    packages:
    - libpq-dev
install: "./scripts/travis-install.sh"
script: py.test --cov=alfacoins
after_success: travis_retry coveralls
deploy:
  provider: pypi
  user: Rhonin
  skip_cleanup: true
  password:
    secure: "bM3SK2h4O8yWEWvg+w3uh8Zp9g2v167pECbDgDKYfRBOHzXXzNVz28XRT3MWb87bw7smup+XH0tGDKxk9SbS+arUVyR08uWY/kuA3Olz5hMf0V4IV2RUy4/qTG9h4RQJN0KullR2K4eITzE4MGixM2Bbh2ofzA9B1AvhnyBZ52gtIpDXXcghNblQA3XE1+qACyRjgIdIOo2jeoQ6NUjWhdUSsD+2CNYONPe/ElKJ/aBHW3V8W+H2DQwcWltxc0Piggay2wokpNysa7uToTvOlkhwKD+38Sr+HF1q9dS4//TEiwRJ7qQNWxvgMu//Ume3xdZaCJDLWdIjJcIqW7d0B4lW6RiBhjWnhra93yOvStsReiEC6TkpqQoTJesw8VShdLs7t6XLv6sj/pFef9OMp3GRkh0ZcDY/V+fvlZjsDORicnNMBphOET7rU1/QUluCuBal4k7tyyyRnID4WXldVLwzFQBnZU8S43Ye2ubEOoGVSdmbjnJqeOzu+0Wn0n06uWHStBT8FjLST/IOAEANp2UNTUmOIpLnKUKpI+z+IP8XoieZOgR51YH/PyhlArKr5vOQPUvBCtnlg8pmapibvZHaOsjLseeIAjdaA1RzUo2rUTaev5meALvl0N04lOB5innPpyATeUiAGuSEv2+xdJWxTgbz2jYfVMgPkVtyInQ="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ArashFatahzade/alfacoins
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
