env:
  global:
  - COMMIT_AUTHOR_EMAIL: arash.fattahzade@carrene.com
language: python
dist: trusty
python: '3.6'
branches:
  only:
  - master
  - nightly
  - "/^v([1-9]\\d*!)?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))*((a|b|rc)(0|[1-9]\\d*))?(\\.post(0|[1-9]\\d*))?(\\.dev(0|[1-9]\\d*))?$/"
addons:
  apt:
    packages:
    - libpq-dev
install: "./scripts/travis-install.sh"
script: py.test --cov=alfacoins
after_success: travis_retry coveralls
deploy:
  provider: pypi
  user: Rhonin
  skip_cleanup: true
  password: Mitik0man
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ArashFatahzade/alfacoins
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
